name: manage-azure-policy-85596e00
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Deny_the_creation_of_public_IP_Deny-PublicIP/**'
#      - 'policies/RDP_access_from_the_Internet_should_be_blocked_Deny-RDP-From-Internet/**'
#      - 'policies/Subnets_should_have_a_Network_Security_Group_Deny-Subnet-Without-Nsg/**'
#      - 'policies/Deploy_an_Azure_DDoS_Protection_Standard_plan_Deploy-DDoSProtection/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Network_Security_Groups_to_Log_Analytics_workspace_Deploy-Diagnostics-NetworkSecurityGroups/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Virtual_Network_to_Log_Analytics_workspace_Deploy-Diagnostics-VirtualNetwork/**'
#      - 'policies/Deploys_NSG_flow_logs_and_traffic_analytics_Deploy-Nsg-FlowLogs/**'
#      - 'policies/Deploys_NSG_flow_logs_and_traffic_analytics_to_Log_Analytics_Deploy-Nsg-FlowLogs-to-LA/**'
#      - .github/workflows/manage-azure-policy-85596e00.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_85596e00}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Deny_the_creation_of_public_IP_Deny-PublicIP/**
          policies/RDP_access_from_the_Internet_should_be_blocked_Deny-RDP-From-Internet/**
          policies/Subnets_should_have_a_Network_Security_Group_Deny-Subnet-Without-Nsg/**
          policies/Deploy_an_Azure_DDoS_Protection_Standard_plan_Deploy-DDoSProtection/**
          policies/Deploy_Diagnostic_Settings_for_Network_Security_Groups_to_Log_Analytics_workspace_Deploy-Diagnostics-NetworkSecurityGroups/**
          policies/Deploy_Diagnostic_Settings_for_Virtual_Network_to_Log_Analytics_workspace_Deploy-Diagnostics-VirtualNetwork/**
          policies/Deploys_NSG_flow_logs_and_traffic_analytics_Deploy-Nsg-FlowLogs/**
          policies/Deploys_NSG_flow_logs_and_traffic_analytics_to_Log_Analytics_Deploy-Nsg-FlowLogs-to-LA/**
